### ISSUE TITLE
Boolean to string convertation issue

### ISSUE THREAD

**Issue by sevrugin** [adnedelcu/reepay-php-api#1]
Hi!

I've found an issue with converting the query parameters from boolean to string.
I'm working with method `getCustomerPaymentMethods($handle, $only_active=true)` and I'd like to fetch only the active payment methods.
Unfortunately, into `ApiClient:199` http_build_query convert $queryParams to string as `only_active=1`
Reepay API recognize only `only_active=true` and never `=1`. In this case it always returns all the methods

**Comment by adnedelcu** [comment]
Hi. Sorry for not answering earlier, but I didn't get a notification.

If you know how to fix it, you could create a pull request and I will be more than glad to merge it.

**Comment by sevrugin** [comment]
Unfortunately currently I couldn't run your tests locally, but in my opinion it should work with the next changes:
ObjectSerializer.php : toString()
```
public function toString($value)
    {
        if ($value instanceof \DateTime) { // datetime in ISO8601 format
            return $value->format(\DateTime::ATOM);
        } elseif (is_bool($value)) {
            return $value? 'true': 'false';
        } else {
            return $value;
        }
    }
```

**Comment by sevrugin** [comment]
https://github.com/adnedelcu/reepay-php-api/pull/2

**Comment by adnedelcu** [comment]
Merged and released. 
Packagist should see the new version already.
If not, then just wait a bit.
